-- CAMPUSHUB DATABASE SETUP
-- Run this entire file in Supabase Dashboard -> SQL Editor.

create table if not exists public.resources (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null check (category in ('Study','Events','Projects','Clubs','Career')),
  url text not null,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.resources enable row level security;

grant select on public.resources to anon, authenticated;
grant insert, update, delete on public.resources to authenticated;

drop policy if exists "Anyone can view resources" on public.resources;
create policy "Anyone can view resources"
on public.resources for select
to anon, authenticated
using (true);

drop policy if exists "Users can add resources" on public.resources;
create policy "Users can add resources"
on public.resources for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their resources" on public.resources;
create policy "Users can update their resources"
on public.resources for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their resources" on public.resources;
create policy "Users can delete their resources"
on public.resources for delete
to authenticated
using (auth.uid() = user_id);

-- Demo data: user_id stays NULL, so these are visible to everyone.
insert into public.resources (title, description, category, url)
select * from (values
  ('Striver A2Z DSA Sheet', 'A structured roadmap for learning data structures and algorithms.', 'Study', 'https://takeuforward.org/strivers-a2z-dsa-course/'),
  ('GitHub Student Developer Pack', 'Free developer tools and services available to eligible students.', 'Career', 'https://education.github.com/pack'),
  ('React Documentation', 'Official React learning material and API reference.', 'Projects', 'https://react.dev/'),
  ('Google Summer of Code', 'Explore open-source contribution opportunities for students.', 'Career', 'https://summerofcode.withgoogle.com/'),
  ('Campus Events Board', 'A placeholder resource for discovering college events and workshops.', 'Events', 'https://www.srmist.edu.in/'),
  ('Project Ideas', 'A starting point for finding project ideas and building a portfolio.', 'Projects', 'https://github.com/topics/project-ideas')
) as seed(title, description, category, url)
where not exists (select 1 from public.resources);